### PR TITLE
For auto-legends with range data, show ≥

### PR DESCRIPTION
**Pull request by mvl22**

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Could you provide a before/after  image to show what this changes? :+1: to merging in any case.

**Comment by mvl22** [comment]
Just adds a ≥ symbol for range types.

I'd like to add more flexibility for the legends generally, as this will be needed when more types are added to the infrastructure types, but for now this at least makes it more correct.

Screenshot 2024-05-27 at 14 07 46

**Comment by Robinlovelace** [comment]
Looks good. I could imagine more specific (e.g. 0 to 900) breaks but this is defo good enough for now I think.

**Comment by mvl22** [comment]
> Looks good. I could imagine more specific (e.g. 0 to 900) breaks but this is defo good enough for now I think.

Yes, that's the kind of thing I'd like to improve and make more configurable. I was keen for now just to ensure it is at least accurate. I plan to refactor the existing legends and stops into the newer system, but that's obviously not sensible to do right before launch. After that's done, configurability will then be more of a priority.

**Pull request merged**
