### PR TITLE
set_image_widths.md

### PR DESCRIPTION
**Pull request by richybu**
Set image widths for 'Quiet/Indirect Fast/Direct', 'Complete network, Simplified Network', and 'Dasymetric' images as they were extending beyond page width.

### CODE REVIEW

**Comment by richybu** [comment]
Hi Martin. On both Safari and Chrome, but perhaps they are not the latest versions, I will test this out and let you know if i am still experiencing it. Yes, it sounds much better if they are set at 100% rather than 1000px, apologies.

**Comment by Robinlovelace** [comment]
Thanks for the contributions @richybu! Will look to discuss how best to go about reviewing and incorporating all these great suggestions tomorrow.

**Comment by Robinlovelace** [comment]
Nudge on this @mvl22 please review and merge/suggest changes as appropriate.

**Comment by mvl22** [comment]
I've pushed a commit which fixes this by applying max-width, as used for the dialogs. This should be preferable to setting exact values.

**Comment by Robinlovelace** [comment]
Great job Martin.

**Pull request closed without merging**
