### PR TITLE
rename pmtiles

### PR DESCRIPTION
**Pull request by wangzhao0217**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
@mvl22 can you check each layer on local version and provide proper code review of this? Lots of changes to the data, should all improve results :pray:

**Comment by mvl22** [comment]
data_zones-2024-12-01.pmtiles does not exist - could you check this is on the server and that is the correct filename?

**Comment by Robinlovelace** [comment]
My bad, will upload...

**Comment by Robinlovelace** [comment]
Should be there now. Will merge and check.

**Pull request merged**
