### PR TITLE
Fix geolocation tooltip; fixes #229

### LINKED ISSUE #229: Geolocate button has no tooltip
Another issue from https://placebasedcarboncalculator.github.io/ that carries across to this tool.

@mvl22 added nice tooltips to the map controls that have three different behaviours depending on the button

Expected behavior: On basemap button. New tooltip

image

Slightly odd: On built-in map libre buttons: A second tooltip appears after a few seconds

image

Broken: On find my location button: Only the second tooltip appears after a few seconds

image

### PR DESCRIPTION
**Pull request by mvl22**
Now fixed, was just an edge-case timing issue. I've forced this to load when the map is ready now, as that should guarantee controls are present.

Screenshot 2024-10-28 at 20 04 33

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]
Doesn't this part duplicate #260 ? Looks good to me in any case.

**Comment by mvl22** [comment]
> Doesn't this part duplicate https://github.com/nptscot/nptscot.github.io/pull/260 ? Looks good to me in any case.

Erm, not sure what happened there, must have switched branches wrongly.

**Comment by Robinlovelace** [comment]
No worries, your call which order to merge them and how to sort out any resulting conflicts. Let's get this on the test website :rocket: and close the associated issues :building_construction:

**Comment by mvl22** [comment]
Please approve the accordion in first.

I don't think there should be any merge conflicts.

**Comment by Robinlovelace** [comment]
Approved and, by the looks of #260, merged.

**Pull request merged**
