### PR TITLE
Add local authorities tab with links to scheme sketcher; refs #245

### PR DESCRIPTION
**Pull request by mvl22**
@Robinlovelace Adds the new tab. Ready for review and merging.

### CODE REVIEW

**Comment by mvl22** [comment]
Screenshot 2024-10-19 at 17 41 47

**Comment by Robinlovelace** [comment]
Will check out and test as follows:

```sh
gh pr checkout 252
```

**Comment by Robinlovelace** [comment]
Cannot see the same thing on my computer running the code in this PR locally:

image

**Comment by Robinlovelace** [comment]
Did you check-in all the files, including the geojson? There seems to be a 404 associated with the geojson file in tests:

image

**Comment by Robinlovelace** [comment]
Works after latest commit. The locally hosted version of the scheme-sketcher didn't work for me but seemed to redirect great. :+1: let's merge it, at your leisure (fine to add the geojson or use the one already hosted online.

**Review by Robinlovelace — APPROVED** [review]

**Comment by mvl22** [comment]
Yes, it assumes the GeoJSON file is present at the path given. Obviously that is the case on the server.

**Pull request merged**
