### PR TITLE
280 local authority links wrong on production

### LINKED ISSUE #277: Traffic layer is hard to find, how best to make it easier to find?
As discussed today during ad-hoc user testing session with @Hussein-Mahfouz, the traffic layer is hard to find. It reminds of the Travel to School layer in the PCT, where the functionality was so hidden that people ended up not using it. As a new user, how would you possibly know to look in "Cycling by Design" if you were looking for current traffic levels?

Unlike many users, Hussein was actually trying to find it and even after a few minutes of clicking around could not (found now with guidance from me during ad-hoc testing).

I'm not sure how best to address this, but simple is good and a safe change would be to simply change the heading of the layer from 

```
Cycling by Design compliance
```

to

```
Level of Service, Traffic, and Infrastructure
```

What do people think? I think naming the widget by its purpose and functionality rather than by the perhaps rather esoteric name of the report on which it is based, could be a quick fix, that actually mentions traffic.

### LINKED ISSUE #280: Local authority links wrong on production
As shown below:

https://www.npt.scot/

Click on Local authorities: From there the links are as follows: https://www.npt.scot/scheme-sketcher/sketch.html?boundary=REGION_Aberdeen%20and%20North%20East 

Which of course are not live.

2 options come to mind, either we

1. remove the Local Authorities tab or we
2. update the URLs.

Thoughts @mvl22 and @dabreegster?

I would err towards the first.

### PR DESCRIPTION
**Pull request by Robinlovelace**
- **Cycling by Design compliance -> Infrastructure and traffic, close #277**
- **Remove LA tab from production version, close #280**

### CODE REVIEW

**Review by mvl22 — COMMENTED** [review]
This looks fine but you also have to remove the nav link from the other pages too. At present these do not use any build system to auto-include a header/footer file.

**Comment by Robinlovelace** [comment]
> This looks fine but you also have to remove the nav link from the other pages too. At present these do not use any build system to auto-include a header/footer file.

Great point. Could you do that @mvl22 ? From cafe..

**Comment by Robinlovelace** [comment]
Nudge @mvl22 can you also incorporate the improvements to the 'cn' layer in #284 ?

**Comment by Robinlovelace** [comment]
Please update and review so I can merge (branch protection rules prevent me from doing so atm).

**Comment by mvl22** [comment]
@Robinlovelace Done. Do merge.

**Comment by Robinlovelace** [comment]
> @Robinlovelace Done. Do merge.

I cannot until you review and Approve the PR without bypassing the branch protenction rules that we have put in place to ensure code review before pushing to prod.

**Comment by Robinlovelace** [comment]
Tested after merging with dev and looking good.

image

**Pull request merged**
