### PR TITLE
Update dataset names

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by mvl22** [comment]
All looks good, and I'm glad to see we finally have those inconsistent capitalisations fully flushed out.

Do obviously just update the dataset names whenever you want - shouldn't need my review.

**Comment by Robinlovelace** [comment]
Yeah we're almost there with new data...

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 this should be working I think, but network datasets are not showing. Any ideas why? 

See https://nptscot.blob.core.windows.net/pmtiles/rnet_simplified_2024-05-23.pmtiles

**Comment by Robinlovelace** [comment]
Update on this @mvl22 this is pretty much good to go, rnet is working. Not sure why simplified network is not. Can you take a quick look?

**Comment by Robinlovelace** [comment]
Working well, fairly non-controversial so going to merge. @mvl22, @wangzhao0217, @joeytalbot can you do a quick sanity check of the updated results on https://nptscot.github.io and let us know ASAP if you find any issues/regressions compared with what's on https://www.npt.scot/#8/55.953/-3.138 ?

**Comment by mvl22** [comment]
> Not sure why simplified network is not.

Looks like you resolved this by putting in the correct name of the internal layer, great.

**Pull request merged**
