### PR TITLE
205 add road type field to most datasets to aid rendering 1

### LINKED ISSUE #205: Add road type field to most datasets, to aid rendering
Most of the line-based layers have the problem that residential/unclassified streets show prominently because they naturally have good cycleability, to the detriment of the main roads.

At present, we have nothing in these datasets to switch on the status of the road, i.e. main vs non-main roads.

So it would be useful to ensure that these datasets all have a field added giving the road status. We can then make various styling changes, in particular making the residential/unclassified streets have a narrower line width. That will massively improve the display in various cases. The road status would not show in popups, etc., rather it would merely be used as a styling hint.

Basically if you can dump into the data a new field which specifies if the Way is a main road*  or not, I can then theoretically style the non-main roads thinner than the main roads.

* (`motorway`/`trunk`/`primary`/`secondary`/`tertiary`, and `motorway_link`/`trunk_link`/`primary_link`/`secondary_link`/`tertiary_link`)

This was originally raised in https://github.com/nptscot/nptscot.github.io/issues/193#issuecomment-2140728648:

> Cycling by design compliance
> We need some way to separate out the data, maybe involving filtering out the majority of residential roads?

### PR DESCRIPTION
**Pull request by Robinlovelace**
- **First pass at updated colours for new infrastructure labels**
- **Update colourscheme**
- **Add highway type, close #205**
- **Use new cbd_layer**
- **Use simple cycle infrastructure value**
- **Attempt to get infrastructure layer working**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 this is all working, except for the colours when selecting existing infra for some reason. Please review, make any necessary changes and merge.

**Comment by mvl22** [comment]
> Heads-up @mvl22 this is all working, except for the colours when selecting existing infra for some reason.

Has the layer name in the data changed, from 'Cycle infrastructure' to 'Infrastructure type', as per the key you have redefined in f060461d98b72c17174410dca4bb00555f753c60? The label can be changed independently if you have not changed the layer name.

**Comment by Robinlovelace** [comment]
Bingo!

image

Please review and merge when ready @mvl22

**Comment by mvl22** [comment]
> Add infra type

Ah right, yes, if the layer name was changed that has to be matched in the drop-down.

(I intend in future to generate the drop-downs from the dataset definitions, so that there is then only a single source of these definitions. The refactoring hasn't quite got that far yet.)

**Comment by Robinlovelace** [comment]
Question for you Martin: where is the best place to explain that

> Separated cycle track means infrastructure that is physically separated from the carriageway and **not** alongside a major road

? 

A popup maybe?

Also see #193 where this may be best placed.

**Comment by Robinlovelace** [comment]
@mvl22 tagging in case you don't see this, I'm hitting the hay z z

**Comment by mvl22** [comment]
> A popup maybe?

Add the definitions to the manual, section 'Cycling by Design compliance', between the `clos` start/finish markers in that file. That is what is then used in the (i) popup.

**Pull request merged**
